#!/bin/bash

. $(dirname ${0})/qa-include

DESC="Removing unwanted files: *.a *.la"

function check() {
	for file in $(find ${BUILDROOT} -name "*.a" -or -name "*.la"); do
	
		# Don't remove libc_nonshared.a. It is used by gcc/ld.
		[ "${file##*/}" = "libc_nonshared.a" ] && continue
		[ "${file##*/}" = "libpthread_nonshared.a" ] && continue
		[ "${file##*/}" = "libgcc.a" ] && continue
		[ "${file##*/}" = "libgcc_eh.a" ] && continue
		[ "${file##*/}" = "libfl_pic.a" ] && continue
		[ "${file##*/}" = "libpython2.6.a" ] && continue
	
		log DEBUG "  Removing: ${file}"
		rm -f ${file} || exit $?
	done
}

run

