#!/bin/bash

COMPRESSOR=xz
COMPRESS_EXT=.xz

echo "Compressing man pages..."

BUILDROOT=${1}
shift

for file in $(find ${BUILDROOT}/usr/share/man -type f); do
	case "${file}" in
		*.gz)
			gzip -d ${file}
			file=${file%*.gz}
			;;
		*.bz2)
			bzip2 -d ${file}
			file=${file%*.bz2}
			;;
	esac

	echo "  Compressing man page ${file//${BUILDROOT}/}..."
	${COMPRESSOR} ${file}
done

for file in $(find ${BUILDROOT}/usr/share/man -type l); do
	link=$(ls -l ${file} | sed -e 's/.* -> //' -e 's/\.\(gz\|Z\|bz2\|xz\|lzma\)$//')
	rm -f ${file}
	b=$(echo ${file} | sed -e 's/\.\(gz\|Z\|bz2\|xz\|lzma\)$//')
	ln -sf ${link}${COMPRESS_EXT} ${b}${COMPRESS_EXT}
done

exit 0
